version: "2"

services:
  nginx:
    build: ./services/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/nginx:/etc/nginx/conf.d
      - ../frontend:/frontend
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - api
      - auth
      - telegram-bot

  mongo:
    build: ./services/mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "127.0.0.1:27017:27017"

  pg:
    build: ./services/pg
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  sphinx:
    build: ./services/sphinx
    ports:
      - "127.0.0.1:9306:9306"
    links:
      - pg
    depends_on:
      - pg
    restart: always

  cropper:
    build: ./services/cropper
    links:
      - mongo
    environment:
      - WAIT_HOSTS=mongo:27017
      - WAIT_BEFORE_HOSTS=5
    ports:
      - "127.0.0.1:8880:8880"
    depends_on:
      - mongo
    restart: always

  api:
    build: ./services/api
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - pg
      - mongo
      - cropper
      - sphinx
      - cache
    links:
      - pg
      - cropper
      - mongo
      - sphinx
      - cache
    restart: always
    environment:
     - WAIT_HOSTS=pg:5432, mongo:27017, cropper:8880, sphinx:9306
     - WAIT_BEFORE_HOSTS=5
     - PSQL_PASSWORD=qwaqwa
     - PSQL_HOST=pg
     - PSQL_USER=postgres
     - MONGO_HOST=mongo
     - SPHINX_HOST=sphinx
     - CROPPER_HOST=cropper

  cache:
    image: memcached:alpine
    ports:
      - "11211"
    command: memcached -m 1024m

  yandex-music-downloader:
    build: ./services/music-downloader
    links:
     - pg
     - mongo
    ports:
      - "127.0.0.1:8020:8020"
    environment:
     - WAIT_HOSTS=pg:5432, mongo:27017
     - WAIT_BEFORE_HOSTS=5
     - PS_HOST=pg
     - MONGO_HOST=mongo
     - PS_USER=postgres
     - PS_PASSWORD=qwaqwa
    depends_on:
     - pg
     - mongo

  auth:
    build: ./services/auth
    ports:
     - "127.0.0.1:9000:9000"
    environment:
     - PS_HOST=pg
     - PS_USER=postgres
     - PS_PASSWORD=qwaqwa
    depends_on:
     - pg

  telegram-bot:
    build: ./services/telegram-bot
    environment:
      TELEGRAM_BOT_NAME: '${TELEGRAM_BOT_NAME}'
      TELEGRAM_BOT_KEY: '${TELEGRAM_BOT_KEY}'

volumes:
  mongo_data:
    external: true
  pg_data:
    external: true

networks:
  default:
    external:
      name: cherry
