version: "2"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    expose:
      - "80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - api

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    expose:
      - "27017"

  pg:
    image: valri/cherry-pg
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - pg_data:/var/lib/postgresql

  sphinx:
    image: valri/cherry-sphinx
    expose:
      - "9312"
      - "9306"
    ports:
      - "9306:9306"
    links:
      - pg
    depends_on:
      - pg
    restart: always

  cropper:
    image: valri/cherry-cropper
    expose:
      - "8880"
    links:
      - mongo
    environment:
      - WAIT_HOSTS=mongo:27017
      - WAIT_BEFORE_HOSTS=5
    ports:
      - "8880:8880"
    depends_on:
      - mongo
    restart: always

  api:
    image: valri/cherry-api
    expose:
      - "5000"
    ports:
      - "5000:5000"
    depends_on:
      - pg
      - mongo
      - cropper
      - sphinx
    links:
      - pg
      - cropper
      - mongo
      - sphinx
    restart: always
    environment:
     - WAIT_HOSTS=pg:5432, mongo:27017, cropper:8880, sphinx:9306
     - WAIT_BEFORE_HOSTS=5
     - PSQL_PASSWORD=qwaqwa
     - PSQL_HOST=pg
     - PSQL_USER=postgres
     - MONGO_HOST=mongo
     - SPHINX_HOST=sphinx
     - CROPPER_HOST=cropper
     - GENIUS_KEY=whl61PGUKPylK_jgfWhWAiuasfHwq1xHxkLBWv-UTuDhGH5n69nkgygEEFivzCXj

  crawler:
    image: valri/cherry-crawler
    links:
     - pg
     - mongo
    environment:
     - WAIT_HOSTS=pg:5432, mongo:27017
     - WAIT_BEFORE_HOSTS=5
     - PS_HOST=pg
     - MONGO_HOST=mongo
     - PS_USER=postgres
     - PS_PASSWORD=qwaqwa
     - GENIUS_TOKEN=whl61PGUKPylK_jgfWhWAiuasfHwq1xHxkLBWv-UTuDhGH5n69nkgygEEFivzCXj
    depends_on:
     - pg
     - mongo

volumes:
  mongo_data:
    external: true
  pg_data:
    external: true
