version: "3"

services:

  mongo:
    build: ./docker/mongo
    volumes:
      - mongo_data:/data/db
    expose:
      - "27017"
    env_file:
      - ./docker/.env

  nginx:
    build: ./docker/nginx
    links:
      - mongo
      - pg
      - streaming
      - search
    ports:
      - "80:80"
    command: /bin/bash -c "nginx -g 'daemon off;'"
    env_file:
      - ./docker/.env

  pg:
    build: ./docker/pg
    expose:
      - "5432"
    volumes:
      - pg_data:/var/lib/postgresql
    env_file:
      - ./docker/.env

  streaming:
    build: ./docker/streaming
    links:
      - pg
      - mongo
    expose:
      - "8080"
    env_file:
      - ./docker/.env

  search:
    build: ./docker/search
    links:
      - pg
      - mongo
    expose:
      - "8080"
    env_file:
      - ./docker/.env

volumes:
  mongo_data:
    external: true
  pg_data:
    external: true
