version: "2"

services:
  nginx:
    build: ./services/nginx
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    volumes:
      - ./services/nginx:/etc/nginx/conf.d
      - ../frontend:/frontend
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - api

  mongo:
    build: ./services/mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    expose:
      - "27017"

  pg:
    build: ./services/pg
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  sphinx:
    build: ./services/sphinx
    expose:
      - "9312"
      - "9306"
    ports:
      - "9306:9306"
    links:
      - pg
    depends_on:
      - pg
    restart: always

  cropper:
    build: ./services/cropper
    expose:
      - "8880"
    links:
      - mongo
    environment:
      - WAIT_HOSTS=mongo:27017
      - WAIT_BEFORE_HOSTS=5
    ports:
      - "8880:8880"
    depends_on:
      - mongo
    restart: always

  api:
    build: ./services/api
    expose:
      - "5000"
    ports:
      - "5000:5000"
    depends_on:
      - pg
      - mongo
      - cropper
      - sphinx
      - cache
    links:
      - pg
      - cropper
      - mongo
      - sphinx
      - cache
    restart: always
    environment:
     - WAIT_HOSTS=pg:5432, mongo:27017, cropper:8880, sphinx:9306
     - WAIT_BEFORE_HOSTS=5
     - PSQL_PASSWORD=qwaqwa
     - PSQL_HOST=pg
     - PSQL_USER=postgres
     - MONGO_HOST=mongo
     - SPHINX_HOST=sphinx
     - CROPPER_HOST=cropper
     - GENIUS_KEY=whl61PGUKPylK_jgfWhWAiuasfHwq1xHxkLBWv-UTuDhGH5n69nkgygEEFivzCXj

  cache:
    image: memcached:alpine
    ports:
      - "11211"
    command: memcached -m 1024m

#  crawler:
#    build: ./services/crawler
#    links:
#     - pg
#     - mongo
#    environment:
#     - WAIT_HOSTS=pg:5432, mongo:27017
#     - WAIT_BEFORE_HOSTS=5
#    - PS_HOST=pg
#     - MONGO_HOST=mongo
#     - PS_USER=postgres
#     - PS_PASSWORD=qwaqwa
#     - GENIUS_TOKEN=whl61PGUKPylK_jgfWhWAiuasfHwq1xHxkLBWv-UTuDhGH5n69nkgygEEFivzCXj
#    depends_on:
#     - pg
#     - mongo

  yandex-music-downloader:
    build: ./services/music-downloader
    links:
     - pg
     - mongo
    expose:
      - "8020"
    ports:
      - "8020:8020"
    environment:
     - WAIT_HOSTS=pg:5432, mongo:27017
     - WAIT_BEFORE_HOSTS=5
     - PS_HOST=pg
     - MONGO_HOST=mongo
     - PS_USER=postgres
     - PS_PASSWORD=qwaqwa
     - GENIUS_TOKEN=whl61PGUKPylK_jgfWhWAiuasfHwq1xHxkLBWv-UTuDhGH5n69nkgygEEFivzCXj
    depends_on:
     - pg
     - mongo

  auth:
    build: ./services/auth

volumes:
  mongo_data:
    external: true
  pg_data:
    external: true

networks:
  default:
    external:
      name: cherry
